### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Imangazaliev**

### CODE REVIEW

**Comment by watson** [comment]
@Imangazaliev thanks :)

Can I get you to make the list of CI servers into a bullet list? When just listing each server on a line by it self like you do here, Markdown will format it as one huge line :(

**Bad:**
```md
foo
bar
baz
```

The above will be rendered as one line: `foo bar baz`

**Good:**
```md
- foo
- bar
- baz
```

**Comment by Imangazaliev** [comment]
Oh yeah, I didn't notice, sorry

**Comment by watson** [comment]
@Imangazaliev Awesome! Thanks again :)

**Comment by watson** [comment]
@Imangazaliev Do you have a URL for the Snip CI server you added? I can't find any reference to it anywhere

**Comment by Imangazaliev** [comment]
No, I do not know where it came from

**Pull request merged**
